import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

// Reliable Unsplash campus/education images
const imgs = [
  "https://images.unsplash.com/photo-1562774053-701939374585?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1541339907198-e08759dfc3ef?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1523050335392-93851179ae22?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1592280771190-3e2e4d571952?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1580537659466-0a9bfa916a54?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1607237138185-eedd9c632b0b?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1574958269340-fa927503f3dd?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1519452635265-7b1fbfd1e4e0?w=800&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1559135197-8a45ea74d367?w=800&auto=format&fit=crop",
];

function img(i: number) { return imgs[i % imgs.length]; }

async function main() {
  console.log("Clearing old data...");
  await prisma.savedCollege.deleteMany();
  await prisma.review.deleteMany();
  await prisma.course.deleteMany();
  await prisma.college.deleteMany();
  await prisma.user.deleteMany();

  const colleges = [
    { name: "Indian Institute of Technology, Bombay", slug: "iit-bombay", location: "Mumbai, Maharashtra", state: "Maharashtra", rating: 4.9, type: "Public", established: 1958, avgPackage: 21.8, highestPackage: 150.0, topRecruiters: "Google, Microsoft, Amazon, Meta, Goldman Sachs", image: img(0), courses: [{ name: "B.Tech Computer Science", duration: "4 Years", fees: 220000 }, { name: "B.Tech Electrical", duration: "4 Years", fees: 220000 }, { name: "M.Tech CSE", duration: "2 Years", fees: 150000 }] },
    { name: "Indian Institute of Technology, Delhi", slug: "iit-delhi", location: "New Delhi, Delhi", state: "Delhi", rating: 4.8, type: "Public", established: 1961, avgPackage: 20.4, highestPackage: 140.0, topRecruiters: "Google, Adobe, Samsung, Flipkart", image: img(1), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 225000 }, { name: "B.Tech Mechanical", duration: "4 Years", fees: 225000 }] },
    { name: "Indian Institute of Technology, Madras", slug: "iit-madras", location: "Chennai, Tamil Nadu", state: "Tamil Nadu", rating: 4.8, type: "Public", established: 1959, avgPackage: 19.0, highestPackage: 120.0, topRecruiters: "Microsoft, Amazon, Qualcomm, Intel", image: img(2), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 210000 }, { name: "B.Tech Data Science", duration: "4 Years", fees: 210000 }] },
    { name: "Indian Institute of Technology, Kanpur", slug: "iit-kanpur", location: "Kanpur, Uttar Pradesh", state: "Uttar Pradesh", rating: 4.7, type: "Public", established: 1959, avgPackage: 18.5, highestPackage: 130.0, topRecruiters: "Apple, Google, Microsoft", image: img(3), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 220000 }] },
    { name: "Indian Institute of Technology, Kharagpur", slug: "iit-kharagpur", location: "Kharagpur, West Bengal", state: "West Bengal", rating: 4.7, type: "Public", established: 1951, avgPackage: 17.2, highestPackage: 110.0, topRecruiters: "TCS, Goldman Sachs, HSBC", image: img(4), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 215000 }] },
    { name: "Indian Institute of Technology, Roorkee", slug: "iit-roorkee", location: "Roorkee, Uttarakhand", state: "Uttarakhand", rating: 4.6, type: "Public", established: 1847, avgPackage: 16.0, highestPackage: 90.0, topRecruiters: "Amazon, Google, Deloitte", image: img(5), courses: [{ name: "B.Tech Civil", duration: "4 Years", fees: 200000 }] },
    { name: "Indian Institute of Technology, Guwahati", slug: "iit-guwahati", location: "Guwahati, Assam", state: "Assam", rating: 4.5, type: "Public", established: 1994, avgPackage: 15.0, highestPackage: 80.0, topRecruiters: "Microsoft, Oracle, Wipro", image: img(6), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 210000 }] },
    { name: "Indian Institute of Technology, Hyderabad", slug: "iit-hyderabad", location: "Hyderabad, Telangana", state: "Telangana", rating: 4.5, type: "Public", established: 2008, avgPackage: 14.5, highestPackage: 70.0, topRecruiters: "Amazon, Microsoft, TCS", image: img(7), courses: [{ name: "B.Tech AI", duration: "4 Years", fees: 220000 }] },
    { name: "BITS Pilani", slug: "bits-pilani", location: "Pilani, Rajasthan", state: "Rajasthan", rating: 4.7, type: "Private", established: 1964, avgPackage: 18.2, highestPackage: 60.0, topRecruiters: "Oracle, NVIDIA, Adobe, Uber", image: img(8), courses: [{ name: "B.E. Computer Science", duration: "4 Years", fees: 550000 }, { name: "B.E. Electronics", duration: "4 Years", fees: 550000 }] },
    { name: "BITS Pilani, Goa Campus", slug: "bits-goa", location: "Goa", state: "Goa", rating: 4.5, type: "Private", established: 2004, avgPackage: 14.0, highestPackage: 45.0, topRecruiters: "Google, Amazon, DE Shaw", image: img(9), courses: [{ name: "B.E. CSE", duration: "4 Years", fees: 540000 }] },
    { name: "NIT Trichy", slug: "nit-trichy", location: "Tiruchirappalli, Tamil Nadu", state: "Tamil Nadu", rating: 4.6, type: "Public", established: 1964, avgPackage: 12.5, highestPackage: 55.0, topRecruiters: "Cognizant, Infosys, TCS, Zoho", image: img(0), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 175000 }, { name: "B.Tech ECE", duration: "4 Years", fees: 175000 }] },
    { name: "NIT Warangal", slug: "nit-warangal", location: "Warangal, Telangana", state: "Telangana", rating: 4.5, type: "Public", established: 1959, avgPackage: 11.8, highestPackage: 48.0, topRecruiters: "Microsoft, Amazon, Wipro", image: img(1), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 165000 }] },
    { name: "NIT Surathkal", slug: "nit-surathkal", location: "Mangalore, Karnataka", state: "Karnataka", rating: 4.5, type: "Public", established: 1960, avgPackage: 12.0, highestPackage: 50.0, topRecruiters: "Oracle, Adobe, Cisco", image: img(2), courses: [{ name: "B.Tech IT", duration: "4 Years", fees: 170000 }] },
    { name: "VIT Vellore", slug: "vit-vellore", location: "Vellore, Tamil Nadu", state: "Tamil Nadu", rating: 4.3, type: "Private", established: 1984, avgPackage: 9.0, highestPackage: 75.0, topRecruiters: "TCS, Wipro, Infosys", image: img(3), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 198000 }, { name: "B.Tech IT", duration: "4 Years", fees: 198000 }] },
    { name: "SRM Institute of Science and Technology", slug: "srm-chennai", location: "Chennai, Tamil Nadu", state: "Tamil Nadu", rating: 4.1, type: "Private", established: 1985, avgPackage: 7.5, highestPackage: 42.0, topRecruiters: "Infosys, TCS, HCL", image: img(4), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 350000 }] },
    { name: "Manipal Institute of Technology", slug: "mit-manipal", location: "Manipal, Karnataka", state: "Karnataka", rating: 4.3, type: "Private", established: 1957, avgPackage: 10.0, highestPackage: 50.0, topRecruiters: "Oracle, SAP, Cisco", image: img(5), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 440000 }] },
    { name: "IIM Ahmedabad", slug: "iim-ahmedabad", location: "Ahmedabad, Gujarat", state: "Gujarat", rating: 4.9, type: "Public", established: 1961, avgPackage: 35.0, highestPackage: 80.0, topRecruiters: "McKinsey, BCG, Goldman Sachs", image: img(6), courses: [{ name: "MBA", duration: "2 Years", fees: 1200000 }] },
    { name: "IIM Bangalore", slug: "iim-bangalore", location: "Bangalore, Karnataka", state: "Karnataka", rating: 4.8, type: "Public", established: 1973, avgPackage: 33.0, highestPackage: 75.0, topRecruiters: "McKinsey, Bain, Amazon", image: img(7), courses: [{ name: "MBA", duration: "2 Years", fees: 1250000 }] },
    { name: "IIM Calcutta", slug: "iim-calcutta", location: "Kolkata, West Bengal", state: "West Bengal", rating: 4.8, type: "Public", established: 1961, avgPackage: 32.0, highestPackage: 70.0, topRecruiters: "BCG, Deloitte, EY", image: img(8), courses: [{ name: "MBA", duration: "2 Years", fees: 1180000 }] },
    { name: "Delhi University", slug: "du-delhi", location: "New Delhi, Delhi", state: "Delhi", rating: 4.4, type: "Public", established: 1922, avgPackage: 8.0, highestPackage: 35.0, topRecruiters: "Deloitte, EY, KPMG", image: img(9), courses: [{ name: "B.Com (Hons)", duration: "3 Years", fees: 25000 }, { name: "BA Economics", duration: "3 Years", fees: 22000 }] },
    { name: "Jadavpur University", slug: "jadavpur-kolkata", location: "Kolkata, West Bengal", state: "West Bengal", rating: 4.4, type: "Public", established: 1955, avgPackage: 10.0, highestPackage: 40.0, topRecruiters: "TCS, Wipro, Cognizant", image: img(0), courses: [{ name: "B.E. CSE", duration: "4 Years", fees: 12000 }] },
    { name: "Anna University", slug: "anna-chennai", location: "Chennai, Tamil Nadu", state: "Tamil Nadu", rating: 4.3, type: "Public", established: 1978, avgPackage: 8.5, highestPackage: 38.0, topRecruiters: "Infosys, CTS, Zoho", image: img(1), courses: [{ name: "B.E. CSE", duration: "4 Years", fees: 52000 }] },
    { name: "Amity University", slug: "amity-noida", location: "Noida, Uttar Pradesh", state: "Uttar Pradesh", rating: 3.9, type: "Private", established: 2005, avgPackage: 6.0, highestPackage: 25.0, topRecruiters: "Wipro, TCS, HCL", image: img(2), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 310000 }] },
    { name: "Lovely Professional University", slug: "lpu-jalandhar", location: "Jalandhar, Punjab", state: "Punjab", rating: 3.8, type: "Private", established: 2005, avgPackage: 5.5, highestPackage: 42.0, topRecruiters: "Amazon, Flipkart, TCS", image: img(3), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 280000 }] },
    { name: "Chandigarh University", slug: "cu-chandigarh", location: "Mohali, Punjab", state: "Punjab", rating: 4.0, type: "Private", established: 2012, avgPackage: 6.5, highestPackage: 50.0, topRecruiters: "Microsoft, Amazon, Google", image: img(4), courses: [{ name: "B.E. CSE", duration: "4 Years", fees: 260000 }] },
    { name: "IIIT Hyderabad", slug: "iiit-hyderabad", location: "Hyderabad, Telangana", state: "Telangana", rating: 4.6, type: "Public", established: 1998, avgPackage: 18.0, highestPackage: 90.0, topRecruiters: "Google, Microsoft, Apple", image: img(5), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 380000 }] },
    { name: "IIIT Bangalore", slug: "iiit-bangalore", location: "Bangalore, Karnataka", state: "Karnataka", rating: 4.4, type: "Public", established: 1999, avgPackage: 15.0, highestPackage: 60.0, topRecruiters: "Adobe, Flipkart, Goldman Sachs", image: img(6), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 350000 }] },
    { name: "Thapar Institute of Engineering", slug: "thapar-patiala", location: "Patiala, Punjab", state: "Punjab", rating: 4.2, type: "Private", established: 1956, avgPackage: 9.5, highestPackage: 45.0, topRecruiters: "Infosys, Wipro, Adobe", image: img(7), courses: [{ name: "B.E. CSE", duration: "4 Years", fees: 350000 }] },
    { name: "PSG College of Technology", slug: "psg-coimbatore", location: "Coimbatore, Tamil Nadu", state: "Tamil Nadu", rating: 4.3, type: "Private", established: 1951, avgPackage: 7.0, highestPackage: 30.0, topRecruiters: "Zoho, CTS, Infosys", image: img(8), courses: [{ name: "B.E. CSE", duration: "4 Years", fees: 95000 }] },
    { name: "RVCE Bangalore", slug: "rvce-bangalore", location: "Bangalore, Karnataka", state: "Karnataka", rating: 4.2, type: "Private", established: 1963, avgPackage: 10.0, highestPackage: 48.0, topRecruiters: "Cisco, Oracle, SAP", image: img(9), courses: [{ name: "B.E. CSE", duration: "4 Years", fees: 250000 }] },
    { name: "College of Engineering, Pune", slug: "coep-pune", location: "Pune, Maharashtra", state: "Maharashtra", rating: 4.4, type: "Public", established: 1854, avgPackage: 11.0, highestPackage: 55.0, topRecruiters: "TCS, Persistent, Infosys", image: img(0), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 120000 }] },
    { name: "VJTI Mumbai", slug: "vjti-mumbai", location: "Mumbai, Maharashtra", state: "Maharashtra", rating: 4.3, type: "Public", established: 1887, avgPackage: 10.5, highestPackage: 45.0, topRecruiters: "JP Morgan, Goldman Sachs", image: img(1), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 98000 }] },
    { name: "NIT Rourkela", slug: "nit-rourkela", location: "Rourkela, Odisha", state: "Odisha", rating: 4.3, type: "Public", established: 1961, avgPackage: 10.0, highestPackage: 42.0, topRecruiters: "TCS, Microsoft, Amazon", image: img(2), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 160000 }] },
    { name: "NIT Calicut", slug: "nit-calicut", location: "Kozhikode, Kerala", state: "Kerala", rating: 4.4, type: "Public", established: 1961, avgPackage: 11.5, highestPackage: 50.0, topRecruiters: "Oracle, TCS, Infosys", image: img(3), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 155000 }] },
    { name: "PESIT Bangalore", slug: "pesit-bangalore", location: "Bangalore, Karnataka", state: "Karnataka", rating: 4.1, type: "Private", established: 1972, avgPackage: 8.0, highestPackage: 40.0, topRecruiters: "SAP, Cisco, Amazon", image: img(4), courses: [{ name: "B.E. CSE", duration: "4 Years", fees: 380000 }] },
    { name: "BMS College of Engineering", slug: "bmsce-bangalore", location: "Bangalore, Karnataka", state: "Karnataka", rating: 4.1, type: "Private", established: 1946, avgPackage: 7.5, highestPackage: 35.0, topRecruiters: "Infosys, Wipro, L&T", image: img(5), courses: [{ name: "B.E. CSE", duration: "4 Years", fees: 250000 }] },
    { name: "Christ University", slug: "christ-bangalore", location: "Bangalore, Karnataka", state: "Karnataka", rating: 4.0, type: "Private", established: 1969, avgPackage: 7.0, highestPackage: 28.0, topRecruiters: "Deloitte, KPMG, EY", image: img(6), courses: [{ name: "BBA", duration: "3 Years", fees: 320000 }, { name: "B.Com", duration: "3 Years", fees: 280000 }] },
    { name: "Symbiosis International University", slug: "symbiosis-pune", location: "Pune, Maharashtra", state: "Maharashtra", rating: 4.2, type: "Private", established: 1971, avgPackage: 12.0, highestPackage: 35.0, topRecruiters: "Accenture, EY, Deloitte", image: img(7), courses: [{ name: "MBA", duration: "2 Years", fees: 1050000 }] },
    { name: "NMIMS Mumbai", slug: "nmims-mumbai", location: "Mumbai, Maharashtra", state: "Maharashtra", rating: 4.3, type: "Private", established: 1981, avgPackage: 14.0, highestPackage: 40.0, topRecruiters: "JP Morgan, HSBC, Deloitte", image: img(8), courses: [{ name: "MBA", duration: "2 Years", fees: 1100000 }] },
    { name: "IIT BHU Varanasi", slug: "iit-bhu", location: "Varanasi, Uttar Pradesh", state: "Uttar Pradesh", rating: 4.5, type: "Public", established: 1919, avgPackage: 15.0, highestPackage: 80.0, topRecruiters: "Google, Microsoft, Samsung", image: img(9), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 220000 }] },
    { name: "IIT Indore", slug: "iit-indore", location: "Indore, Madhya Pradesh", state: "Madhya Pradesh", rating: 4.3, type: "Public", established: 2009, avgPackage: 13.0, highestPackage: 55.0, topRecruiters: "Amazon, Google, Microsoft", image: img(0), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 210000 }] },
    { name: "DAIICT Gandhinagar", slug: "daiict-gandhinagar", location: "Gandhinagar, Gujarat", state: "Gujarat", rating: 4.2, type: "Private", established: 2001, avgPackage: 10.0, highestPackage: 40.0, topRecruiters: "TCS, Oracle, Adobe", image: img(1), courses: [{ name: "B.Tech ICT", duration: "4 Years", fees: 260000 }] },
    { name: "IIIT Delhi", slug: "iiit-delhi", location: "New Delhi, Delhi", state: "Delhi", rating: 4.5, type: "Public", established: 2008, avgPackage: 17.0, highestPackage: 80.0, topRecruiters: "Google, Samsung, Amazon", image: img(2), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 350000 }] },
    { name: "DTU Delhi", slug: "dtu-delhi", location: "New Delhi, Delhi", state: "Delhi", rating: 4.4, type: "Public", established: 1941, avgPackage: 12.0, highestPackage: 60.0, topRecruiters: "Microsoft, Samsung, Adobe", image: img(3), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 170000 }] },
    { name: "NSUT Delhi", slug: "nsut-delhi", location: "New Delhi, Delhi", state: "Delhi", rating: 4.3, type: "Public", established: 1983, avgPackage: 11.0, highestPackage: 55.0, topRecruiters: "Amazon, Google, TCS", image: img(4), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 165000 }] },
    { name: "LNMIIT Jaipur", slug: "lnmiit-jaipur", location: "Jaipur, Rajasthan", state: "Rajasthan", rating: 4.0, type: "Private", established: 2003, avgPackage: 8.5, highestPackage: 35.0, topRecruiters: "Amazon, Oracle, TCS", image: img(5), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 290000 }] },
    { name: "IIIT Allahabad", slug: "iiit-allahabad", location: "Prayagraj, Uttar Pradesh", state: "Uttar Pradesh", rating: 4.3, type: "Public", established: 1999, avgPackage: 12.0, highestPackage: 50.0, topRecruiters: "Microsoft, Amazon, Samsung", image: img(6), courses: [{ name: "B.Tech IT", duration: "4 Years", fees: 180000 }] },
    { name: "Shiv Nadar University", slug: "snu-noida", location: "Greater Noida, Uttar Pradesh", state: "Uttar Pradesh", rating: 4.1, type: "Private", established: 2011, avgPackage: 11.0, highestPackage: 45.0, topRecruiters: "Microsoft, Amazon, Deloitte", image: img(7), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 450000 }] },
    { name: "Ashoka University", slug: "ashoka-sonipat", location: "Sonipat, Haryana", state: "Haryana", rating: 4.2, type: "Private", established: 2014, avgPackage: 10.0, highestPackage: 30.0, topRecruiters: "McKinsey, BCG, Goldman Sachs", image: img(8), courses: [{ name: "BA Economics", duration: "3 Years", fees: 500000 }] },
    { name: "NIT Durgapur", slug: "nit-durgapur", location: "Durgapur, West Bengal", state: "West Bengal", rating: 4.1, type: "Public", established: 1960, avgPackage: 8.0, highestPackage: 35.0, topRecruiters: "TCS, CTS, Wipro", image: img(9), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 155000 }] },
    { name: "NIT Jaipur", slug: "nit-jaipur", location: "Jaipur, Rajasthan", state: "Rajasthan", rating: 4.2, type: "Public", established: 1963, avgPackage: 9.5, highestPackage: 40.0, topRecruiters: "Amazon, Adobe, Oracle", image: img(0), courses: [{ name: "B.Tech CSE", duration: "4 Years", fees: 160000 }] },
  ];

  for (const { courses, ...data } of colleges) {
    const c = await prisma.college.create({ data: { ...data, courses: { create: courses } } });
    console.log(`✓ ${c.name}`);
  }
  console.log(`\n✅ Seeded ${colleges.length} colleges!`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
